### ISSUE TITLE
OKD instructions not accessible

### ISSUE THREAD

**Issue by brenthdaniel** [microservices-api/kubernetes-microprofile-lab#23]
The readme section on setting up a cluster refers to vLaunch VMs and has a link to an internal website.

**Comment by navidsh** [comment]
Thx @brenthdaniel. Updated the lab.

------

## Setting up an OKD cluster

Follow instructions in [Install Red Hat OKD 3.11 on CentOS](https://github.com/gshipley/installcentos). If you are provided other instructions on this part, follow them instead.
