### ISSUE TITLE
not doable

### ISSUE THREAD

**Issue by chenrulai** [microservices-api/kubernetes-microprofile-lab#6]
the instructions not detailed enough to make it doable.
For example, which os and version is this doc based on? various version can introduce considerable challenges.

**Comment by arthurdm** [comment]
The has been tested in Mac OS, Ubuntu and Windows.  Basically any OS that can install the required software can run the lab.

**Comment by arthurdm** [comment]
I added this clarification at the end of Step 0: https://github.com/microservices-api/kubernetes-microprofile-lab/blob/master/README.md#step-0-before-you-begin
